name: Missing Service Call
description: Service call is missing in Ryujinx.
labels: not-implemented
body:
  - type: textarea
    id: instruction
    attributes:
      label: Service call
      description: What service call is missing?
    validations:
      required: true
  - type: textarea
    id: name
    attributes:
      label: Service description
      description: Include the description/explanation from [Switchbrew](https://switchbrew.org/w/index.php?title=Services_API) and/or [SwIPC](https://reswitched.github.io/SwIPC/) in the above code block
    validations:
      required: true
  - type: textarea
    id: required
    attributes:
      label: Required by
      description:  Add links to the [compatibility list page(s)](https://github.com/Ryujinx/Ryujinx-Games-List/issues) of the game(s) that require this service.
    validations:
      required: true