name: Mako
on:
  discussion:
    types: [created, edited, answered, unanswered, category_changed]
  discussion_comment:
    types: [created, edited]
  gollum:
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened, edited, reopened, pinned, milestoned, demilestoned, assigned, unassigned, labeled, unlabeled]
  pull_request_target:
    types: [opened, edited, reopened, synchronize, ready_for_review, assigned, unassigned]

jobs:
  tasks:
    name: Run Ryujinx tasks
    permissions:
      actions: read
      contents: read
      discussions: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request_target'
        with:
          # Ensure we pin the source origin as pull_request_target run under forks.
          fetch-depth: 0
          repository: Ryujinx/Ryujinx
          ref: master

      - name: Run Mako command
        uses: Ryujinx/Ryujinx-Mako@master
        with:
          command: exec-ryujinx-tasks
          args: --event-name "${{ github.event_name }}" --event-path "${{ github.event_path }}" -w "${{ github.workspace }}" "${{ github.repository }}" "${{ github.run_id }}"
          app_id: ${{ secrets.MAKO_APP_ID }}
          private_key: ${{ secrets.MAKO_PRIVATE_KEY }}
          installation_id: ${{ secrets.MAKO_INSTALLATION_ID }}
